### ISSUE TITLE
Add ability to load last actor/task run dataset

### ISSUE THREAD

**Issue by drobnikj** [apify/keboola-ex-apify#33]
Notes from Slack https://apifier.slack.com/archives/C010Q0FBYG3/p1639993254172700
Apify-Keboola uploader - missing feature
We came across the need which IMO is crucial for many users using both Apify and Keboola, which is to upload to keboola last run of actor/task (at the moment you can either call the actor, which unneccessarily consumes user's recources on both Keboola and Apify sides) or get data from dataset (which is cool but if you want to do it everyday you must either use a named dataset and the ammount of data is growing really fast or set a new id every day - not realistic).
Can we add it to the integration? I think @jakubdrobnik has worked on it before.
Also if you can navigate us to the code, @Martina G. might be able to add it herself, as she has just overcame this hurdle by setting a generic API extractor on Keboola's side.

**Comment by MartinaGelnerova** [comment]
Currently the Keboola Apify extractor allows following options:
- run actor/task which is time=credit consuming
- retreive items from dataset based on its id (one time upload) or name (repeated uploads from named dataset - this again gets time/credit consuming with instantly growing dataset)
Completely missing is option to retreive dataset from last run which would mean optimal usage of uploader (no time waiting for actor/task to finish, only last values are imported).
I have worked it around with generic extractor - json to be found here:
https://drive.google.com/file/d/1hpbk_qvDyl6sLC79Ju2-7AuaYXYFAvN1/view?usp=sharing

**Comment by drobnikj** [comment]
Duplicate of #40

**Comment by drobnikj** [comment]
done in #43

**Comment by drobnikj** [comment]
done in https://github.com/apify/keboola-ex-apify/pull/43
