### ISSUE TITLE
The new actor was not started if previous timed out

### ISSUE THREAD

**Issue by drobnikj** [apify/keboola-ex-apify#36]
The broken flow TBD by @sestys

**Comment by sestys** [comment]
I'm using Apify component in Keboola to schedule a run. If the actor run times-out on apify platform, the runId stays saved in the keboola component state, which causes the next component job to try and access the previous run, not to start a new one.

Can be fixed to by manually clearing the component state.

![image](https://user-images.githubusercontent.com/70316007/213496752-7603cd32-4e94-4e00-adee-abcd5c71562c.png)
