### ISSUE TITLE
Input is set even there is no input

### ISSUE THREAD

**Issue by drobnikj** [apify/keboola-ex-apify#9]
In case, where user didn't fill input. It should be empty, but now it is set to:
```
{
  "inputTableRecord": {}
}
```

**Comment by cybairfly** [comment]
In order for input schema default inputs to kick in, assuming that's how it would work then.

**Comment by gippy** [comment]
If actor has input schema and you remove input, it create the input for the actor with default values. Can you provide more context for this issue? @drobnikj

**Comment by drobnikj** [comment]
Fixed in https://github.com/apify/keboola-ex-apify/commit/cf3cca98a7229dc200bebd12c507dfa719c0c812
